In [40]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [41]:
time = pd.read_csv('messages.csv')
date = pd.read_csv('orders.csv')

In [42]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [43]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [44]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [45]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

# working with dates

In [46]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [47]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [48]:
# extract year 
date['date_year'] = date['date'].dt.year

In [49]:
# extract month 
date['date_month'] = date['date'].dt.month

In [50]:
# extract month name 
date['month_name'] = date['date'].dt.month_name()

In [51]:
# extract days 
date['date_days'] = date['date'].dt.day

In [52]:
# day of week 
date['date_weekday'] = date['date'].dt.dayofweek

In [53]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,month_name,date_days,date_weekday
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [54]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,month_name,date_days,date_weekday,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [55]:
# is weekend 
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0) 
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,month_name,date_days,date_weekday,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [56]:
# extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week

In [57]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,month_name,date_days,date_weekday,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [58]:
# extract quarter 
date['quarter'] = date['date'].dt.quarter

In [59]:
# extract semester 
date['Semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,month_name,date_days,date_weekday,date_dow_name,date_is_weekend,date_week,quarter,Semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

# Extract Time Elapsed Betweeem dates

In [60]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 6, 7, 16, 48, 27, 848715)

In [61]:
today - date['date']

0     2371 days 16:48:27.848715
1     2853 days 16:48:27.848715
2     2784 days 16:48:27.848715
3     2486 days 16:48:27.848715
4     2709 days 16:48:27.848715
                 ...
995   2799 days 16:48:27.848715
996   2740 days 16:48:27.848715
997   2588 days 16:48:27.848715
998   2653 days 16:48:27.848715
999   2427 days 16:48:27.848715
Name: date, Length: 1000, dtype: timedelta64[ns]

In [62]:
(today - date['date']).dt.days

0      2371
1      2853
2      2784
3      2486
4      2709
       ...
995    2799
996    2740
997    2588
998    2653
999    2427
Name: date, Length: 1000, dtype: int64

In [63]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [64]:
# converting to datetime datatype

In [65]:
time['date'] = pd.to_datetime(time['date'])

In [66]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [67]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [68]:
time

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0
...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,0,50,0
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23,14,0
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23,37,0
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23,34,0
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23,25,0

In [69]:
time['time'] = time['date'].dt.time

In [70]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

# Time difference

In [71]:
today - time['date']

0     4557 days 15:58:27.848715
1     4421 days 17:08:27.848715
2     4907 days 16:27:27.848715
3     4209 days 16:17:27.848715
4     4606 days 17:37:27.848715
                 ...
995   5196 days 15:58:27.848715
996   4517 days 17:34:27.848715
997   4982 days 17:11:27.848715
998   5098 days 17:14:27.848715
999   4370 days 17:23:27.848715
Name: date, Length: 1000, dtype: timedelta64[ns]

In [72]:
# in seconds
(today - time['date'])/np.timedelta64(1,'s')

0      3.937823e+08
1      3.820361e+08
2      4.240240e+08
3      3.637162e+08
4      3.980218e+08
           ...
995    4.489919e+08
996    3.903321e+08
997    4.305067e+08
998    4.405293e+08
999    3.776306e+08
Name: date, Length: 1000, dtype: float64

In [73]:
# in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      6.563038e+06
1      6.367268e+06
2      7.067067e+06
3      6.061937e+06
4      6.633697e+06
           ...
995    7.483198e+06
996    6.505534e+06
997    7.175111e+06
998    7.342154e+06
999    6.293843e+06
Name: date, Length: 1000, dtype: float64

In [75]:
# in hours
(today - time['date'])/np.timedelta64(1,'h')

0      109383.974402
1      106121.141069
2      117784.457736
3      101032.291069
4      110561.624402
           ...
995    124719.974402
996    108425.574402
997    119585.191069
998    122369.241069
999    104897.391069
Name: date, Length: 1000, dtype: float64