In [13]:
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import pandas as pd

# S-1 ) IMPORT LIBRARIES

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
data = pd.read_csv('logistic_regression_dataset.csv')

In [16]:
data

   Hours_Studied  Sleep_Hours  Pass
0            1.0            5     0
1            2.0            6     0
2            2.5            5     0
3            3.0            6     0
4            4.0            6     1
5            5.0            7     1
6            6.0            7     1
7            7.0            8     1
8            8.0            7     1
9            9.0            8     1

In [9]:
# FOR EX - Dew Point Temp_C,Wind Speed_km/h.... etc are input features and Weather is target/output

In [17]:
# S- 3 SEPERATE FEATURE AND TARGET 
x = data.drop('Pass',axis = 1)
y = data['Pass']

In [ ]:
# s- 4 PERFORM TRAIN - TEST SPLIT

In [18]:
X_train , X_test , y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [19]:
X_train

   Hours_Studied  Sleep_Hours
5            5.0            7
0            1.0            5
7            7.0            8
2            2.5            5
9            9.0            8
4            4.0            6
3            3.0            6
6            6.0            7

In [20]:
X_test

   Hours_Studied  Sleep_Hours
8            8.0            7
1            2.0            6